
#define LEVEL_NORMAL			0	//Player
#define LEVEL_GM				1	//Game Master
#define LEVEL_ADMIN				2	//Admin
#define LEVEL_HEADADMIN			3	//Head Admin

#define LOG_FILE_SYSTEM			"/Logs/System.txt"
#define LOG_FILE_HACK			"/Logs/HackDetect.txt"

#define MYSQL_CFG_FILE			"/Config/MySQL.cfg"
#define ADM_CFG_FILE			"/Config/Dump.cfg"

#define DUMP_FILE_ERROR			"/Dump/Error.dmp"
#define DUMP_FILE_PLAYER		"/Dump/Players.dmp"

#define CONQUEROR_SHIELD		(2500.0)

#define ChampionPublic::%0(%1) hook %0(%1) 

